apiVersion: v1
kind: Namespace
metadata:
  name: app-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
  namespace: app-namespace
  labels:
    app: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata: 
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world-container
        image: otel-logs-ingestion-app:latest # must be loaded into minikube
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000