apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: app-namespace
spec:
  config: 
    # -------------------------------- receivers
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    # -------------------------------- processors
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 80
        spike_limit_percentage: 15
    # -------------------------------- exporters
    exporters:
      debug:
        verbosity: normal
    # -------------------------------- service
    service:
      pipelines:
        logs:
          receivers: [otlp]
          processors: [memory_limiter]
          exporters: [debug]